# central weighted wavelength only; can lead to inaccuracies
monochromatic_observing_filters_lm:
  short-L: 3.29e-6
  Lp: 3.82e-6
  L_spec: 3.56e-6
  Mp: 4.76e-6
  M_spec: 4.87e-6
  Br_alpha: 4.06e-6
  Br_alpha_ref: 3.93e-6
  PAH_3.3: 3.31e-6
  PAH_3.3_ref: 3.45e-6
  CO_1-0_ice: 4.66e-6
  CO_ref: 4.94e-6
  H2O-ice: 3.09e-6
  IB_4.05: 4.04e-6
  HCI_L_short: 3.62e-6
  HCI_L_long: 3.80e-6
  HCI_M: 4.95e-6

# file names of actual filter curves
## ## TODO: MAKE THIS MORE ELEGANT LATER, WITH A SINGLE STEM
polychromatic_observing_filters_lm:
  short-L: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_short-L.dat'
  Lp: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_Lp.dat'
  L_spec: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_L_spec.dat'
  Mp: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_Mp.dat'
  M_spec: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_M_spec.dat'
  Br_alpha: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_Br_alpha.dat'
  Br_alpha_ref: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_Br_alpha_ref.dat'
  PAH_3.3: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_PAH_3.3.dat'
  PAH_3.3_ref: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_PAH_3.3_ref.dat'
  CO_1-0_ice: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_CO_1-0_ice.dat'
  CO_ref: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_CO_ref.dat'
  H2O-ice: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_H2O-ice.dat'
  IB_4.05: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_IB_4.05.dat'
  HCI_L_short: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_HCI_L_short.dat'
  HCI_L_long: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_HCI_L_long.dat'
  HCI_M: '/podman-share/metis_work/notebook_working_dir/inst_pkgs/METIS/filters/TC_filter_HCI_M.dat'


pixel_scales:
  img_lm: 5.47
  img_n: 6.79

D_aperture:
  full: 34.6878
  D_obscuration: 12.8502

# p. 8 in E-REP-ULG-MET-1033 1-0 01/08/2022:
#  full: 36.876
#  D_obscuration: 10.053
# based on numbers from RvB, 2 Mar 2026:
#  full: 34.6878
#  D_obscuration: 12.8502