# FOV simulation run configurations
# Paths are relative to the project stem
# Each run inherits defaults; override only what differs

defaults:
  pp_mask: PPS-CFO2
  config_coords_guesses_file_name: config/config_file_IMG_01_coords.yaml
  results_write_dir: IMG_OPT_01_METIS_AIT_img_cal_fov_SIM_data/

simulation_configs:
  - obs_filter_name: Br_alpha
    obs_filter_file_name: '/METIS/filters/Br_alpha.dat'
    fpmask: pinhole_lm
    pp_mask: PPS-CFO2
    nd_filter: null
    dit: 0.065
    ndit: 2
    exptime: np.nan
    obs_mode: wcu_img_lm
    illuminated_pixels_x: 1920 # pixel length of active on-sky area of detector
    illuminated_pixels_y: 1920
    use_exp_time_only: False
    file_name_abs_trunc: /podman-share/metis_work/playing_with_scopesim/IMG_OPT_01_METIS_AIT_img_cal_fov_SIM_data/IMG_OPT_01_METIS_AIT_img_cal_fov_filter_Br_alpha_simmed_ # suffix will include the dither index

  - obs_filter_name: N2
    obs_filter_file_name: '/METIS/filters/TC_filter_N2.dat'
    fpmask: pinhole_n
    pp_mask: PPS-CFO2
    nd_filter: ND_OD2
    dit: 0.3
    ndit: 2
    exptime: np.nan
    obs_mode: wcu_img_n
    illuminated_pixels_x: 1990 # pixel length of active on-sky area of detector
    illuminated_pixels_y: 1990
    use_exp_time_only: False
    file_name_abs_trunc: /podman-share/metis_work/playing_with_scopesim/IMG_OPT_01_METIS_AIT_img_cal_fov_SIM_data/IMG_OPT_01_METIS_AIT_img_cal_fov_filter_N2_simmed_
